export const ADD_ADDRESS_BOOK = 'ADD_ADDRESS_BOOK'
export const SET_SELECTED_ADDRESS_BOOK_INDEX = 'SET_SELECTED_ADDRESS_BOOK_INDEX'
export const SET_ADDRESS_BOOK_FILTERED = 'SET_ADDRESS_BOOK_FILTERED'
export const SET_DARK_MODE = 'SET_DARK_MODE'
